version: '3.4'

services:
  sts-server:
    build:
      context: ./aspnet-core/services/Publish/identityserver
    volumes:
      - D:\Project\Abp\logs\ids-sts:/app/Logs
      - D:\Project\Abp\data\ids-sts\Modules:/app/Modules
    networks:
      - framework

  sts-api:
    build:
      context: ./aspnet-core/services/Publish/identityserver4-admin
    volumes:
      - D:\Project\Abp\logs\ids-admin:/app/Logs
      - D:\Project\Abp\data\ids-admin\Modules:/app/Modules
    depends_on:
      - sts-server
    networks:
      - framework

  admin-api:
    build:
      context: ./aspnet-core/services/Publish/admin
    volumes:
      - D:\Project\Abp\logs\backend-admin:/app/Logs
      - D:\Project\Abp\data\backend-admin\Modules:/app/Modules
    depends_on:
      - sts-server
    networks:
      - framework

  localization-api:
    build:
      context: ./aspnet-core/services/Publish/localization
    volumes:
      - D:\Project\Abp\logs\localization:/app/Logs
      - D:\Project\Abp\data\localization\Modules:/app/Modules
    depends_on:
      - sts-server
    networks:
      - framework

  platform-api:
    build:
      context: ./aspnet-core/services/Publish/platform
    volumes:
      - D:\Project\Abp\logs\platform:/app/Logs
      - D:\Project\Abp\data\platform\Modules:/app/Modules
      - D:\Project\Abp\data\platform:/app/file-blob-storing
    depends_on:
      - sts-server
    networks:
      - framework

  messages-api:
    build:
      context: ./aspnet-core/services/Publish/messages
    volumes:
      - D:\Project\Abp\logs\messages:/app/Logs
      - D:\Project\Abp\data\messages\Modules:/app/Modules
    depends_on:
      - sts-server
    networks:
      - framework

  task-api:
    build:
      context: ./aspnet-core/services/Publish/task-management
    volumes:
      - D:\Project\Abp\logs\task-management:/app/Logs
      - D:\Project\Abp\data\task-management\Modules:/app/Modules
    depends_on:
      - sts-server
    networks:
      - framework

  webhook-api:
    build:
      context: ./aspnet-core/services/Publish/webhooks
    volumes:
      - D:\Project\Abp\logs\webhooks:/app/Logs
      - D:\Project\Abp\data\webhooks\Modules:/app/Modules
    depends_on:
      - sts-server
    networks:
      - framework

  workflow-api:
    build:
      context: ./aspnet-core/services/Publish/workflow
    volumes:
      - D:\Project\Abp\logs\workflow:/app/Logs
      - D:\Project\Abp\data\workflow\Modules:/app/Modules
    depends_on:
      - sts-server
    networks:
      - framework

  internal-apigateway:
    build:
      context: ./aspnet-core/services/Publish/internal-apigateway
    volumes:
      - D:\Project\Abp\logs\internal-apigateway:/app/Logs
      - D:\Project\Abp\data\internal-apigateway\Modules:/app/Modules
      - D:\Project\Abp\data\internal-apigateway\OcelotConfig:/app/OcelotConfig
    networks:
      - framework
      
volumes:
  dbdata:

networks:
  framework:
    name: nt
    external: true
